name: Update Version

on:
  push:
    branches:
      - main

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Set up Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      
      - name: Update version
        run: |
          current_version=$(cat version.txt)
          echo "Current version: $current_version"
          
          IFS='.' read -ra VERSION_PARTS <<< "$current_version"
          major=${VERSION_PARTS[0]}
          minor=${VERSION_PARTS[1]}
          patch=${VERSION_PARTS[2]}
          
          commit_message=$(git log -1 --pretty=%B)
          
          if [[ $commit_message == *"#major"* ]]; then
            new_version="$((major + 1)).0.0"
          else
            new_version="$major.$((minor + 1)).0"
          fi
          
          echo "New version: $new_version"
          echo "$new_version" > version.txt
          
          git add version.txt
          git commit -m "Bump version to $new_version"
          git push
